---
train:
  params:
    batch_size: 32
    epoch: 30
    lr: 0.0001
    decay: 0.5
    decay_step: 5000
    loss: MSELoss
  save:
    save_path: "/weights/ge_weights/mpii"
  data:
    image: "/Data/mpiigaze/Image"
    label: "/Data/mpiigaze/Label"
